### ISSUE TITLE
There seems to be a bug with selecting text on last line of page when caret is on that line.

### ISSUE THREAD

**Issue by annix-markcl** [Satchelmouth/Obsidian-Theme-WYConsole#1]
Workaround would be to add a new line, then you can select text normally again.

But would be good if it would be fixed.

**Comment by annix-markcl** [comment]
Also text selection invisible on code blocks. (```)

**Comment by andreyc0d3r** [comment]
Same issue @Satchelmouth

**Comment by Satchelmouth** [comment]
Both issues should now be fixed
